# Generated by Django 6.0.4 on 2026-04-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=42, verbose_name='Имя задачи')),
                ('description', models.TextField(blank=True, default='', max_length=700, verbose_name='Описание задачи')),
                ('tags', models.CharField(blank=True, choices=[('work', 'Работа'), ('home', 'Дом'), ('my_tasks', 'Мои задачи')], default='my_tasks', max_length=20, verbose_name='Тег')),
                ('progress', models.IntegerField(choices=[(0, 'Активная'), (1, 'В процессе'), (2, 'Выполнена'), (3, 'Провалена'), (4, 'Отложена')], default=0, verbose_name='Прогресс')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-id'],
            },
        ),
    ]
