# Generated by Django 6.0.4 on 2026-04-15 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=42, verbose_name='Имя задачи')),
                ('description', models.TextField(max_length=700, null=True, verbose_name='Описание задачи')),
                ('tags', models.TextField(choices=[('work', 'Работа'), ('home', 'Дом'), ('my_tasks', 'Мои задачи')], null=True, verbose_name='Теги')),
                ('progress', models.IntegerField(choices=[(0, 'Активная'), (1, 'В процессе'), (2, 'Выполнена'), (3, 'Провалена'), (4, 'Отложена')], default=0, verbose_name='Прогресс')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='Автор задачи')),
            ],
        ),
    ]
